[project]
name = "instafix-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp[speedups]>=3.11.14",
    "fastapi[standard]>=0.115.12",
    "jinja2>=3.1.6",
    "msgspec>=0.19.0",
    "selectolax[cython]>=0.3.28",
]
